# docker-compose.yml (top level)
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: fastapi
    ports:     
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d fastapi"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: 
      context: .
      args:
        GIT_SHA: "Unknown"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+asyncpg://app:app@db:5432/fastapi
      SECRET_KEY: ${SECRET_KEY:-dev123}
    ports: ["8000:8000"]
    volumes:
      - ./logs:/app/logs
    restart: on-failure

  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring:/etc/prometheus
    ports: ["9090:9090"]

  grafana:
    image: grafana/grafana
    depends_on: [prometheus]
    ports: ["3000:3000"]
